spring:

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/profiles
    username: postgres
    password: postgres

---
spring:
  profiles: dev

  sql:
    init:
      mode: always

---
spring:
  profiles: prod

  sql:
    init:
      mode: never